# Generated by Django 3.1.6 on 2021-12-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0012_auto_20211205_2044'),
        ('makeReports', '0011_auto_20211205_2102'),
    ]

    operations = [
    ]
